[package]
name = "gpu-worker-ort"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "gpu worker for onnx"
repository = "https://github.com/wavey-ai/gpu-workers"
readme = "README.md"

[dependencies]
anyhow = "1.0"
ort = { version = "2.0.0-rc.12", default-features = false, features = [
    "std",
    "ndarray",
    "tracing",
    "download-binaries",
    "tls-native",
    "copy-dylibs",
    "api-24",
    "load-dynamic",
    "tensorrt",
    "cuda",
    "coreml",
] }

